AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      
  SafetyGearDetector:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: safetygeardetector:latest
      Timeout: 900
      MemorySize: 10048
      Events:
        ApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: ANY
