AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FlaskApi:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ImageUri: safetygeardetector:latest
      MemorySize: 3008
      Timeout: 300
      Environment:
        Variables:
          UPLOAD_FOLDER: /tmp/uploads
          OUTPUT_FOLDER: /tmp/output
      Events:
        Index:
          Type: Api
          Properties:
            Path: /
            Method: GET
        